### ISSUE TITLE
Nottinghamshire site still exists, but shouldn't

### ISSUE THREAD

**Issue by abimysoc** [mysociety/petitions#59]
They cancelled in 2013.

**Comment by stevenday** [comment]
We can't really close this down because it's part of a multi-site council set up, and one of the sub-councils, east-northants, still pay their bills (afaik). 

The same is true of mansfield, bassetlaw and rushcliffe, as per this comment on the original ticket to close them: https://github.com/mysociety/petitions/issues/32#issuecomment-35073231
